"""Actualizando tablas y columnas locales

Revision ID: 438dfee9f739
Revises: d5adf64aae2d
Create Date: 2026-07-07 16:50:29.251092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438dfee9f739'
down_revision = 'd5adf64aae2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_importbolts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('prefijo', sa.String(length=5), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('prefijo')
    )
    op.create_table('product_importbolts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=False),
    sa.Column('calidad', sa.String(length=200), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('unidades_por_caja', sa.Integer(), nullable=True),
    sa.Column('precio_unidad', sa.Float(), nullable=True),
    sa.Column('precio_docena', sa.Float(), nullable=True),
    sa.Column('precio_caja', sa.Float(), nullable=True),
    sa.Column('costo_referencial', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('actualizado_por', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('product_movement_importbolts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=True),
    sa.Column('stock_nuevo', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_importbolts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desc_tipo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('desc_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desc_label', sa.String(length=100), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('calidad',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('ubicacion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('ubicacion',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('calidad',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_column('desc_label')
        batch_op.drop_column('desc_valor')
        batch_op.drop_column('desc_tipo')
        batch_op.drop_column('precio_base')

    op.drop_table('product_movement_importbolts')
    op.drop_table('product_importbolts')
    op.drop_table('category_importbolts')
    # ### end Alembic commands ###
