"""Agregado estado y auditoria a tabla productos

Revision ID: d5adf64aae2d
Revises: 
Create Date: 2026-06-19 11:23:21.974268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5adf64aae2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actualizado_por', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('actualizado_por')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
